Explode on missing extent object implementation
Well, there it is...

    Traceback (most recent call last):
      File "[...]/examples/show_block_group_contents.py", line 15, in <module>
        load_data_refs, load_metadata_refs):
      File "[...]/examples/btrfs/ctree.py", line 459, in extents
        Key(header.objectid, header.type, header.offset)))
    Exception: BUG: unexpected object (38027264 SHARED_BLOCK_REF 37863424)

Non-inline SHARED_BLOCK_REF and TREE_BLOCK_REF are totally missing, and
were completely ignored.

Let's fix this!