btrfs-search-metadata: catch BrokenPipeError
When piping btrfs-search-metadata output through for example the head
program, we would get this:

    Uncaught error, please report as bug:
    Traceback (most recent call last):
      File "./btrfs-search-metadata", line 329, in <module>
        main()
      File "./btrfs-search-metadata", line 315, in main
        output_fn(presets[preset][0](fs, **vars(args)))
      File "/home/knorrie/s/python-btrfs/bin/btrfs/utils.py", line 699, in str_print
        print(line)
    BrokenPipeError: [Errno 32] Broken pipe

Instead, silence the error, since the tool is only meant to be used in a
manual way and it's usually intentional when this happens.