Split inline and non-inline shared data backrefs
...because they have different structures.

Inline shared data backref has the parent vaddr and count in a 12 byte
data struct.

btrfs-debug-tree output:

    item 21 key (1095270400 EXTENT_ITEM 4096) itemoff 11798 itemsize 170
        extent refs 10 gen 5367 flags DATA
        extent data backref root 319 objectid 364 offset 811008 count 1
        shared data backref parent 257671823360 count 1
        shared data backref parent 257572962304 count 1
        shared data backref parent 256916684800 count 1
        shared data backref parent 256394035200 count 1
        shared data backref parent 256350732288 count 1
        shared data backref parent 256175030272 count 1
        shared data backref parent 256063127552 count 1
        shared data backref parent 255867125760 count 1
        shared data backref parent 255734349824 count 1

our output:

    extent vaddr 1095270400 length 4096 refs 10 gen 5367 flags DATA
        extent data backref root 319 objectid 364 offset 811008 count 1
        inline shared data backref parent 257671823360 count 1
        inline shared data backref parent 257572962304 count 1
        inline shared data backref parent 256916684800 count 1
        inline shared data backref parent 256394035200 count 1
        inline shared data backref parent 256350732288 count 1
        inline shared data backref parent 256175030272 count 1
        inline shared data backref parent 256063127552 count 1
        inline shared data backref parent 255867125760 count 1
        inline shared data backref parent 255734349824 count 1

Separate shared data ref has the parent vaddr in the offset field of the
object key, and has only count as 4 byte data.

btrfs-debug-tree output:

    item 24 key (1095282688 EXTENT_ITEM 4096) itemoff 11642 itemsize 24
        extent refs 10 gen 5367 flags DATA
    item 25 key (1095282688 EXTENT_DATA_REF 1540237839462548629) itemoff 11614 itemsize 28
        extent data backref root 319 objectid 381 offset 49152 count 1
    item 26 key (1095282688 SHARED_DATA_REF 255732039680) itemoff 11610 itemsize 4
        shared data backref count 1
    item 27 key (1095282688 SHARED_DATA_REF 255858376704) itemoff 11606 itemsize 4
        shared data backref count 1
    item 28 key (1095282688 SHARED_DATA_REF 256062242816) itemoff 11602 itemsize 4
        shared data backref count 1
    item 29 key (1095282688 SHARED_DATA_REF 256159612928) itemoff 11598 itemsize 4
        shared data backref count 1
    item 30 key (1095282688 SHARED_DATA_REF 256315342848) itemoff 11594 itemsize 4
        shared data backref count 1
    item 31 key (1095282688 SHARED_DATA_REF 256380633088) itemoff 11590 itemsize 4
        shared data backref count 1
    item 32 key (1095282688 SHARED_DATA_REF 256915406848) itemoff 11586 itemsize 4
        shared data backref count 1
    item 33 key (1095282688 SHARED_DATA_REF 257569013760) itemoff 11582 itemsize 4
        shared data backref count 1
    item 34 key (1095282688 SHARED_DATA_REF 257659355136) itemoff 11578 itemsize 4
        shared data backref count 1

our output:

    extent vaddr 1095282688 length 4096 refs 10 gen 5367 flags DATA
        extent data backref root 319 objectid 381 offset 49152 count 1
        shared data backref parent 255732039680 count 1
        shared data backref parent 255858376704 count 1
        shared data backref parent 256062242816 count 1
        shared data backref parent 256159612928 count 1
        shared data backref parent 256315342848 count 1
        shared data backref parent 256380633088 count 1
        shared data backref parent 256915406848 count 1
        shared data backref parent 257569013760 count 1
        shared data backref parent 257659355136 count 1

I subclassed the InlineSharedDataRef from SharedDataRef, so that
isinstance(ref, btrfs.ctree.SharedDataRef) still gives True

Without this change, non-inline shared data backrefs could not be loaded
at all:

    Traceback (most recent call last):
      File "./bla.py", line 12, in <module>
        load_data_refs, load_metadata_refs):
      File "/home/knorrie/src/git/python-btrfs/examples/btrfs/ctree.py", line 454, in extents
        extent.append_shared_data_ref(header, data)
      File "/home/knorrie/src/git/python-btrfs/examples/btrfs/ctree.py", line 613, in append_shared_data_ref
        self.shared_data_refs.append(SharedDataRef(data, 0))
      File "/home/knorrie/src/git/python-btrfs/examples/btrfs/ctree.py", line 637, in __init__
        self.parent, self.count = SharedDataRef.shared_data_ref.unpack_from(data, pos)
    struct.error: unpack_from requires a buffer of at least 12 bytes