python3 compatibility, again
Commit 52c3677 "Fix unicode array type error for python 2.7.9" fixed
array.array for older python 2.7, but broke it for python 3 at the same
time.

Introduce more ugly code to work around the python API breakage.

When using python 3:

    Traceback (most recent call last):
      [...]
      File "/home/knorrie/src/git/python-btrfs/examples/btrfs/ioctl.py", line 75, in create_buf
        return array.array(b'B', itertools.repeat(0, size))
    TypeError: array() argument 1 must be a unicode character, not bytes